repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        args: ['--config=setup.cfg', '--count', '--select=E9,F63,F7,F82', '--show-source', '--statistics']

  # isort and black seem incompatible at the moment
  # They fight over white space so this always give an error
  # ignore for now
  # See here
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.21-2
  #   hooks:
  #     - id: isort
  #       additional_dependencies: [toml]
  #       exclude: ^.*/?setup\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: ^tests/.
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
